### ISSUE TITLE
AppStateObserver calling `applicationState` in background thread

### ISSUE THREAD

**Issue by DarthMike** [WalletConnect/WalletConnectSwiftV2#685] opened 2023-01-23 15:47 UTC
**Describe the bug**
AppStateObserver calling code not on main thread. (See screenshot)

**SDK Version**
1.3.0

**To Reproduce**
Go to background to disconnect socket, or wait until socket disconnects from dapp

**Expected behavior**
The warning should not appear

**Screenshots**

![Screenshot 2023-01-23 at 16 45 35](https://user-images.githubusercontent.com/1030987/214083592-49012e1c-96f0-4e4b-b1d8-361b8505c420.png)

**Device (please complete the following information):**
 - Device: Simulator
 - OS: iOS16.2

**Comment by llbartekll** [comment] 2023-01-24 12:33
@DarthMike thanks for reporting this

**Comment by llbartekll** [comment] 2023-03-14 13:14
hey @DarthMike the issue is fixed in 1.5.1

**Closed** 2023-03-14 13:15 UTC
Labels: bug
